### ISSUE TITLE
integer division or modulo by zero

### ISSUE THREAD

**Issue by combatopera** [combatopera/pym2149#22]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/arc/opt/miniconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/arc/opt/miniconda/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/arc/projects/pym2149/pym2149/midi.py", line 191, in __call__
    self.stream.call(block)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 38, in call
    return self(block, False)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/jackclient.py", line 91, in callimpl
    outbufs = [self.chain(wav) for wav in self.wavs]
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/out.py", line 173, in callimpl
    naivebuf = self.chain(self.naive)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/mix.py", line 97, in trivialcallimpl
    for buf in self.chain(self.container):
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/ym2149.py", line 135, in callimpl
    result = Container.callimpl(self)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 59, in callimpl
    return [self.chain(node) for node in self.nodes]
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/dac.py", line 97, in callimpl
    self.blockbuf.mapbuf(self.chain(self.level), self.leveltopeaktopeak)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/dac.py", line 48, in callimpl
    self.blockbuf.copybuf(self.chain(self.signal))
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/mix.py", line 42, in callimpl
    self.blockbuf.copybuf(self.chain(self.tone))
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/osc.py", line 157, in callimpl
    self.chain(self.derivative)(self.blockbuf)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/osc.py", line 75, in callimpl
    stepcount = (self.block.framecount - stepindex + self.stepsize - 1) // self.stepsize
ZeroDivisionError: integer division or modulo by zero
```

**Comment by combatopera** [comment]
this is due to a fancy instrument that has an ever-increasing vibrato, that eventually lets the period hit 0. the period should be clamped to 1 (and 4095).

**Comment by combatopera** [comment]
max period should be configurable as you can get some nasty sounds in the high thousands

**Comment by combatopera** [comment]
related to #50

**Comment by combatopera** [comment]
period clamped in logical reg, with max configurable. closing
