### ISSUE TITLE
crash when using Concern

### ISSUE THREAD

**Issue by combatopera** [combatopera/pym2149#52]
```
Exception in thread EventPump:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/midi.py", line 230, in __call__
    self.stream.call(block)
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 38, in call
    return self(block, False)
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/portaudio.py", line 118, in callimpl
    self.filler([self.chain(wav) for wav in self.wavs])
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/portaudio.py", line 118, in <listcomp>
    self.filler([self.chain(wav) for wav in self.wavs])
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/out.py", line 169, in callimpl
    naivebuf = self.chain(self.naive)
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/mix.py", line 97, in trivialcallimpl
    for buf in self.chain(self.container):
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/ym2149.py", line 141, in callimpl
    maskable(self.block, True) # The masked flag tells the node we don't care about output.
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pym2149/pym2149/osc2.py", line 47, in callimpl
    self.index, self.progress, self.stepsize = self.shapeimpl()
  File "/home/andrzej/opt/Concern-a6b81a8/projects/pyrbo/pyrboimpl/pyrboimpl.py", line 376, in <lambda>
    return lambda *args, **kwargs: self.f(instance, *args, **kwargs)
  File "projects/pym2149/pym2149/osc2_turbo/shapeimpl.pyx", line 15, in pym2149.osc2_turbo.shapeimpl.shapeimpl
OverflowError: value too large to convert to npy_uint32
```

**Comment by combatopera** [comment]
might not really be line 15, but if it is, could be a dupe of #22

**Comment by combatopera** [comment]
optimistically closing as there's not a lot of context here, and the codebase is now much better at clamping register values. reopen if it happens again
