### ISSUE TITLE
cannot cast crash when using Concern

### ISSUE THREAD

**Issue by combatopera** [combatopera/pym2149#62]
```
Exception in thread Player:
Traceback (most recent call last):
  File "/home/arc/opt/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/arc/opt/miniconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/arc/projects/splut/bg.py", line 69, in target
    result = targetimpl(*args, **kwargs)
  File "/home/arc/projects/pym2149/pym2149/ymplayer.py", line 61, in __call__
    self.stream.call(b)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 38, in call
    return self(block, False)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/jackclient.py", line 64, in callimpl
    self.filler([self.chain(wav) for wav in self.wavs])
  File "/home/arc/projects/pym2149/pym2149/jackclient.py", line 64, in <listcomp>
    self.filler([self.chain(wav) for wav in self.wavs])
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/out.py", line 169, in callimpl
    naivebuf = self.chain(self.naive)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/mix.py", line 97, in trivialcallimpl
    for buf in self.chain(self.container):
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/ym2149.py", line 160, in callimpl
    result = super().callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 59, in callimpl
    return [self.chain(node) for node in self.nodes]
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 59, in <listcomp>
    return [self.chain(node) for node in self.nodes]
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/dac.py", line 95, in callimpl
    self.blockbuf.mapbuf(self.chain(self.level), self.leveltopeaktopeak)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 50, in chain
    return node(self.block, self.masked)
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 44, in __call__
    self.result = self.callimpl()
  File "/home/arc/projects/pym2149/pym2149/nod.py", line 76, in makeresult
    resultornone = self.realcallimpl()
  File "/home/arc/projects/pym2149/pym2149/dac.py", line 47, in callimpl
    self.blockbuf.mul(level4to5(self.fixedreg.value))
  File "/home/arc/projects/pym2149/pym2149/buf.py", line 102, in mul
    self.buf *= value
TypeError: Cannot cast ufunc multiply output from dtype('int16') to dtype('uint8') with casting rule 'same_kind'
```

**Comment by combatopera** [comment]
strongly suspect this is related to env+tone bass - nope, this is entirely due to setting a level to -1, which should not be allowed

**Comment by combatopera** [comment]
also see #50

**Comment by combatopera** [comment]
fixed, user value is rounded and clamped in link to emulation reg
