### ISSUE TITLE
gcd import error on python >= 3.9

### ISSUE THREAD

**Issue by cyberic99** [combatopera/pym2149#81]
```
Traceback (most recent call last):
  File "/home/eric/tmp/pym/venvname/bin/ym2txt", line 5, in <module>
    from pym2149.main import main_ym2txt
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/pym2149/main.py", line 18, in <module>
    from . import minblep, pitch
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/pym2149/minblep.py", line 21, in <module>
    from mynblep.minblep import MinBleps
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/mynblep/minblep.py", line 21, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
(venvname) [eric@pc-eric venvname]$ vim /home/eric/tmp/pym/venvname/lib/python3.9/site-packages/mynblep/minblep.py
```

I got this error on archlinux, on python 3.9.

I was able to fix this issue with the following path:

```patch
diff --git a/lib/python3.9/site-packages/mynblep/minblep.py b/lib/python3.9/site-packages/mynblep/minblep.py
index 715daf7..69ab82c 100644
--- a/lib/python3.9/site-packages/mynblep/minblep.py
+++ b/lib/python3.9/site-packages/mynblep/minblep.py
@@ -18,7 +18,11 @@
 from .paste import pasteminbleps
 from .shapes import floatdtype
 from .util import atomic
-from fractions import gcd
+try:
+    from fractions import gcd
+except ImportError:
+    # python >= 3.9
+    from math import gcd
 from pathlib import Path
 import logging, numpy as np, pickle
```

would you like me to create a pull request?

**Comment by combatopera** [comment]
hi @cyberic99, thanks for the bug report. yes, please create a pull request, it should be against the mynblep project https://github.com/combatopera/mynblep

**Comment by cyberic99** [comment]
I have created the pull request above. Thank you.

**Comment by combatopera** [comment]
thanks. that is now merged and released in mynblep 12, which should be picked up by new installs of pym2149. you may have to upgrade mynblep manually in existing venvs
