### ISSUE TITLE
lha import error

### ISSUE THREAD

**Issue by cyberic99** [combatopera/pym2149#82]
I get this error on archlinux, on python 3.9:
```
ym2txt file.ym
```
```
[DEBUG] > Request: pym2149.iface.Config
[DEBUG] > Fabricate: pym2149.iface.Config
[WARNING] Settings not found: [Errno 2] No such file or directory: '/home/eric/.settings.arid'
[DEBUG] > Request: Started[pym2149.ymformat.YMOpen](Started)
[DEBUG] >> Request: pym2149.ymformat.YMOpen
[DEBUG] >> Instantiate: pym2149.ymformat.YMOpen
[DEBUG] > Instantiate: Started[pym2149.ymformat.YMOpen]
[DEBUG] Deleting temporary folder: /tmp/tmpwf3exu5i
Traceback (most recent call last):
  File "/home/eric/tmp/pym/venvname/bin/ym2txt", line 8, in <module>
    sys.exit(main_ym2txt())
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/pym2149/main.py", line 244, in main_ym2txt
    di.all(Started)
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/diapyr/diapyr.py", line 106, in all
    return AllInstancesOf(type).getall(self, self.depthunit)
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/diapyr/match.py", line 26, in getall
    return [source.make(depth, self.clazz) for source in di.typetosources.get(self.clazz, [])]
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/diapyr/match.py", line 26, in <listcomp>
    return [source.make(depth, self.clazz) for source in di.typetosources.get(self.clazz, [])]
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/diapyr/source.py", line 61, in make
    instance = self.callable(*args)
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/diapyr/start.py", line 35, in __init__
    startable.start()
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/pym2149/ymformat.py", line 277, in start
    self.startimpl()
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/pym2149/ymformat.py", line 293, in startimpl
    self.f = UnpackedFile(self.path)
  File "/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/pym2149/ymformat.py", line 314, in __init__
    from lagoon import lha
ImportError: cannot import name 'lha' from 'lagoon' (/home/eric/tmp/pym/venvname/lib/python3.9/site-packages/lagoon/__init__.py)
```
I can't find any mention of lha in lagoon lib...

and even after manually uncompressing my ym file, I still get the error.

Thanks

**Comment by combatopera** [comment]
Hi @cyberic99, there are 2 issues here
* lagoon is an interface to commands available on your system, it's complaining because you don't have the lha command. i believe the package you want to install is `lhasa`
* pym2149 should detect when a ym file is already unpacked, and apparently this has been broken for some time. i've pushed a fix to head and will release it asap

**Comment by combatopera** [comment]
i've
* added a note to lagoon readme for what to do if you see ImportError
* released the fix for uncompressed ym file detection in pym2149 version 26

**Comment by cyberic99** [comment]
Thank you.
I confirm that after installing lha and updating the repo, I can now dump both compressed and uncompressed .ym files.
